server:
  port: 9090
  
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/orders/**
        filters:
        - name: CircuitBreaker
          args:
            name: ORDER-SERVICE
            fallbackuri: forward:/orderServiceFallBack
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 1
      - id: PRODUCT-SERVICE 
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/products/**
        filters:
        - name: CircuitBreaker
          args:
            name: PRODUCT-SERVICE
            fallbackuri: forward:/productServiceFallBack
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 1
      - id: PAYMENT-SERVICE
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment/**
        filters:
        - name: CircuitBreaker
          args:
            name: PAYMENT-SERVICE
            fallbackuri: forward:/paymentServiceFallBack
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}    
      
management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [application_name=${spring.application.name} trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags}] %p"

okta:
  oauth2:
    issuer: https://dev-50976627.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaarthyyfQSlKpDa5d7
    client-secret: VR2cstpTpN1XDBxUAkdnh749ngOEFo1XCfCRMKZMAbzLNJcIXgBru3Jk-LfsORW0
    scopes: openid, profile, email, offline_access  
#  config:
#    import: configserver:http://localhost:9296
          
